### ISSUE TITLE
RandonPlay example Issue random and Sound repeating , possible Fix

### ISSUE THREAD

**Issue by koogar** [sleemanj/JQ6500_Serial#16]
Hi James,

I noticed the RandonPlay example uses "pseudo random"  
You end up with a mathematical pattern, so every reset you get the same set of numbers generated.

adding randomseed makes for a better output (not sure how this would work on the ESP)

`
      randomSeed(analogRead(A0));  // mitigate "pseudo random" by sampling the noise on analogue pin0 and use it as a value.`

     pick = random(1, numFiles + 1);
    } while (pick == mp3.currentFileIndexNumber(mediaType));
`

Also "mp3.playFileByIndexNumber(pick);" followed by  "mp3.play();" often causes the file to repeat immediate.
As soon as I removed "mp3.play();" the issue was resolved.

Thanks for your hard work

Rupert

**Comment by sleemanj** [comment]
Done & fixed
