### ISSUE TITLE
JQ6500 Flash Size

### ISSUE THREAD

**Issue by derrgis** [sleemanj/JQ6500_Serial#18]
Hello,
I'm currently working with 50 JQ6500 and I'm using sleemanj lib. that works great.
But it is not clear what the Flash Size of the module. Is there a command to know what is it ?
Mine is a 25L1606E model, I thought it was 2 MB but it seems less. 1MB seems okay, I'm about to test more.
Upload and adjust soundfiles duration is a boring user job for a test. A request to the JQ for Flash size would be easier. Please tell me if this is not the right place to ask this.

**Comment by sleemanj** [comment]
No, there is no command over the serial protocol to get the size that I am aware of.

The command line linux tool which can do so (over the USB connection):

   https://chiselapp.com/user/rmax/repository/jq6500/home

If you use windows then @NikolaiRadke has instructions:

  https://github.com/NikolaiRadke/JQ6500-rescue-tool#how-to-use-the-tool-with-windows

In short, the IC 25L1606E  indicates 16 MegaBIT version I think that the upload tool itself consumes maybe 256kB, and perhaps there is some other overhead associated with the filesystem structure itself.  I'd guess at perhaps 1.5-1.7 Megabytes available for files,
