### ISSUE TITLE
Loop modes behavior

### ISSUE THREAD

**Issue by derrgis** [sleemanj/JQ6500_Serial#22]
This is probably an issue in my code but just to be sure ...

I'm not able to get the MP3_LOOP_ONE working ( same track repeating).
I can monitor that the swicth case occurs but the play command is executed only once. 

Question : Is it possible to change the loop mode at run time or is there something special to do  to swicth between modes 11 4 and 11 2 ?

```
if (global_enabled) {//avoid playing at startup, only if mqtt publication

      switch(holdit)
      {
      //MP3_LOOP_ONE_STOP: ONE_STOP does not loop, plays the track and stops
      //7E 3 11 4  EF
      case 0 : mp3.setLoopMode(MP3_LOOP_ONE_STOP); break; 
     
      
      //MP3_LOOP_ONE : ONE plays the same track repeating
      //7E 3 11 2  EF
      case 1 :  mp3.setLoopMode(MP3_LOOP_ONE); 
      }
  mp3.setVolume(volume);
  byte stat = mp3.getStatus();
 
  if(stat != MP3_STATUS_PLAYING) 
  {
    mp3.playFileByIndexNumber(soundfile);
    }
  }
global_enabled = false;
```

**Comment by sleemanj** [comment]
I do not recall.

Try the Full Demo to test loop one mode without your code.

it may be that playing by index number cancels loop mode perhaps, you could try play by index number, then change loop mode, rather than the other way around - just guessing though.

**Comment by derrgis** [comment]
Everything works fine for all that. Thanks for all sleemanj :) Best.
