### ISSUE TITLE
Baudrate

### ISSUE THREAD

**Issue by yashatan** [sleemanj/JQ6500_Serial#26]
Hello, thank you for your repo.
Can you help me about baud rate of JQ6500. I've tried default 9600 baud rate, it works great. But when i tried higher baud rate: 38400, 115200,... It didn't work. So can it really can works with higher baud rate than 9600? Or i have to set its baud rate somewhere else first?
Thank you very much.

**Comment by sleemanj** [comment]
9600 is fixed in the device I believe, I do not know a way to modify it.
