### ISSUE TITLE
Allow the use of different Serial/Software serial libraries via Stream object

### ISSUE THREAD

**Issue by lucadentella** [sleemanj/JQ6500_Serial#28]
Hi!

I was using your library for a project based on esp32 chip and I was tempted to use one of the available hardware ports.
I slightly modified the library (see [my fork](https://github.com/lucadentella/JQ6500_Serial)) to be able to use a generic **Stream** object. In this way, users can decide which Serial/library to use.

What do you think about it? I faced some problems in the past using SoftwareSerial (conflicts with Servo library...). 
Thanks

**Comment by thijstriemstra** [comment]
+1 for me, can you make a pull request @lucadentella?

**Comment by lucadentella** [comment]
Done, #32

**Comment by sleemanj** [comment]
The PR is merged.
