### ISSUE TITLE
Arduino library download link broken

### ISSUE THREAD

**Issue by michael-zock** [sleemanj/JQ6500_Serial#31]
http://sparks.gogo.co.nz/JQ6500_Serial.zip no longer returns a ZIP file (if it ever did) and the link on https://sparks.gogo.co.nz/docs-and-downloads.html returns people to https://github.com/sleemanj/JQ6500_Serial/blob/master/README.md and merely sends them in circles.

**Comment by michael-zock** [comment]
Works in Edge, but not in Chrome. Weird!

**Comment by sleemanj** [comment]
Works for me, Chrome
