### ISSUE TITLE
Use github pages for api documentation

### ISSUE THREAD

**Issue by thijstriemstra** [sleemanj/JQ6500_Serial#33]
Instead of using githack, serve the docs folder using github pages instead. This would simplify URL and give docs a proper home.

**Comment by thijstriemstra** [comment]
the api docs link in the readme is outdated now. this ticket would fix it and avoid url updates after api doc updates.

**Comment by sleemanj** [comment]
Complete

**Comment by thijstriemstra** [comment]
awesome!
