### ISSUE TITLE
Question - How to change JQ6500 device baud rate permanently?

### ISSUE THREAD

**Issue by mst0mst** [sleemanj/JQ6500_Serial#36]
Greetings Sleemanj,

This is more a question than an issue, sorry if there is another way to communicate between GitHub users...

Do you know the way to permanently change the JQ6500 MP3 player module baud rate?

I am in the need to interface it with a very ancient system, its maximum UART operation can reach 4800 bps instead the JQ6500 default.

I am aware of the man in the middle solution, use a microcontroller, but this solution appears to be a waste of resources for only a serial port input, followed by a slower serial port output.

Thanks in advance!

**Comment by sleemanj** [comment]
AFAIK, not possible.
