### ISSUE TITLE
JQ6500_Error

### ISSUE THREAD

**Issue by 1502adi** [sleemanj/JQ6500_Serial#37]
When I compile code on Arduino Nano I get following error:
no matching function for call to JQ6500_Serial::JQ6500_Serial(int, int)

Please help me to solve this error!

**Comment by sleemanj** [comment]
The interface changed, you should instantiate like this now (for SoftwareSerial)/...    SoftwareSerial mySerial(8, 9);
    JQ6500_Serial mp3(mySerial);
 ---- On Wed, 05 Jan 2022 20:10:55 +1300  ***@***.***  wrote ----
When I compile code on Arduino Nano I get following error:
no matching function for call to JQ6500_Serial::JQ6500_Serial(int, int)
Please help me to solve this error!

**Comment by 1502adi** [comment]
Now it shows another error:
'class JQ6500_Serial' has no member named 'begin'

Thank You !

**Comment by sleemanj** [comment]
See the HelloWorld example for how to use it.

**Comment by 1502adi** [comment]
Awesome, thanks!
