### ISSUE TITLE
JQ6500 -16p Set default volume

### ISSUE THREAD

**Issue by beikimajid** [sleemanj/JQ6500_Serial#43]
Hello, how can I set jq6500-16p in standalone mode so that its volume is the highest level by default (even after power cut) (volume 30)?

**Comment by sleemanj** [comment]
I don't think that is possible.

**Comment by beikimajid** [comment]
Good. If not, is there a way to design a button for the jq6500-16p that starts playback by pressing it and increases the volume by holding the same button for a few seconds?

**Comment by sleemanj** [comment]
No.  You should use a microcontroller to control it over the serial protocol then you can do whatever you want.

**Comment by beikimajid** [comment]
If you read [this document](https://sparks.gogo.co.nz/jq6500/index.html), you will notice that there is another comment in the "Simple Control with Manual Buttons To Ground" section(work with microswitch without microcontroller serial protocol and in standalone mode)
But on jq6500-16p, I don't know on which port the volume increase is done. I tested the pause-play key and it worked

**Comment by sleemanj** [comment]
On the 16 you need to use ADKEY method.

**Comment by beikimajid** [comment]
> On the 16 you need to use ADKEY method.

on 28 work with microswitch?

**Comment by sleemanj** [comment]
All the information is in that document, which I wrote.  There is nothing more to add than is in that document.
