### ISSUE TITLE
Which of these boards is newer?

### ISSUE THREAD

**Issue by beikimajid** [sleemanj/JQ6500_Serial#44]
I got the jq6500-16p ver2.1 from two different stores. But one of them does not work in adkey function. Which of these boards is newer and why is one of them not working?
It's like they have different chip despite the same version! The method of printing jq6500-16p V2.1 text on the boards is also different. Pay attention to the pictures
The second one works with two AA batteries and adkey, but the first board does not work and shuts down(JQ6500-24SS chip)
![Screenshot_2024-06-14-21-37-47-206_ir eitaa messenger-edit](https://github.com/sleemanj/JQ6500_Serial/assets/3895372/923904f3-02d7-4cf6-8b93-48b7d11fc60d)
![Screenshot_2024-06-14-21-37-26-909_ir eitaa messenger-edit](https://github.com/sleemanj/JQ6500_Serial/assets/3895372/a5fdfab8-28b8-4d8f-aff8-d35d69a5d7cf)

**Comment by sleemanj** [comment]
You can see that the second one does not use a JQ6500 at all, but an AS21CN270C if you google you will find that is typically sold as the dfplayer.


JQ6500 information may not be valid for it, no way of knowing.
