### ISSUE TITLE
need_help_identifying_this_chip

### ISSUE THREAD

**Issue by beikimajid** [sleemanj/JQ6500_Serial#45]
Hi, can you identify this chip(AB23A795852.1-74) that is on the jq6500-16p?

![IMG_20240615_232242](https://github.com/sleemanj/JQ6500_Serial/assets/3895372/87ed0662-68e5-4123-aa3e-c7b8ceec58ab)

**Comment by sleemanj** [comment]
Use google.  Not a bug.

**Comment by beikimajid** [comment]
unfortunately there is nothing on Google and it seems that this chip is coded by JL

**Comment by sleemanj** [comment]
https://www.google.com/search?q=%22AB23A79%22

You can see in results it is used as one of the DFPlayer Mini variants.
