### ISSUE TITLE
Real data is different than the protocol document

### ISSUE THREAD

**Issue by roadcontrolsystems** [sleemanj/JQ6500_Serial#8]
Hi,
When I debug the data which is sent by the arduino, I see that actual message frame is the short version of the frame indicated in the datasheet. Version and the checksum fields are missing.

What should I do to run the module with full frame communication?

Edit: I see that current protocol is based on this chinese document.
http://images.100y.com.tw/pdf_file/40-JQ6500-24SS.pdf

Thanks.

**Comment by sleemanj** [comment]
Is the device you have not functioning with the command frames the library sends?

**Comment by roadcontrolsystems** [comment]
I am sorry by opening this issue. I mixed the current protocol with the MP3-TF-16P MP3 Module's protocol which is very similar and extended version of this protocol.

For example, to reset the module, I was expecting to see " 7E FF 06 0C 00 00 00 FE EF EF" but library sends "7E 02 0C 7E ".
